- name: create temporary dir
  tempfile:
    state: directory
    suffix: deploji_
  register: tempdir

- name: Template stack files
  template:
    src: "{{item}}"
    dest: "{{tempdir.path}}/"
  with_fileglob: "stacks/{{app}}/*"

- name: Deploy stack
  shell: docker stack deploy -c docker-compose.yml {{environment_name}}_{{app}}
  args:
    chdir: "{{tempdir.path}}"
  environment:
    SERVICE_VERSION: "{{version}}"
