version: "3.7"
services:
  traefik:
    image: traefik:${SERVICE_VERSION}
    command:
      - "-c=/traefik.toml"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefixStrip:/traefik/"
        - "traefik.port=8080"
    configs:
      - source: traefik_conf3
        target: /traefik.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/acme
    networks:
      - net

networks:
  net:
    name: traefik_net

configs:
  traefik_conf3:
    file: ./traefik.toml

volumes:
  acme:
